org.gradle.caching=true
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
fabric.loom.multiProjectOptimisation=true

project.group=com.iamkaf.torchtoss
project.plugins=3.0-SNAPSHOT

mod.name=Torch Toss
mod.authors=iamkaf
mod.id=torchtoss
mod.license=MIT
mod.credits=
mod.description=A mod about throwing torches.

publish.dry-run=false
publish.curseforge.id=1191803
publish.modrinth.id=AIYW9sHq
publish.release-type=release
publish.game-versions=auto
environments.client=required
environments.server=required

mixin.compat.common=JAVA_18
mixin.compat.fabric=JAVA_21
mixin.compat.forge=JAVA_18
mixin.compat.neoforge=JAVA_21
