project.minecraft=1.16.3
project.java=16
project.build-java=21
project.enabled-loaders=fabric
project.catalog-name=libsMc1163
project.catalog-coordinate=com.iamkaf.platform:mc-1.16.3:1.16.3-SNAPSHOT
mod.minecraft-range=[1.16.3, 1.17)
mod.fabric-range=>=1.16.3
mixin.compat.common=JAVA_16
mixin.compat.fabric=JAVA_16
mixin.compat.forge=JAVA_16
mixin.compat.neoforge=JAVA_16

dependencies.curseforge.required=amber-lib
dependencies.modrinth.required=amber
project.version=5.0.0+1.16.3
