project.version=5.0.0+1.20.6
project.java=21
project.build-java=21
project.minecraft=1.20.6
project.enabled-loaders=fabric,forge
project.catalog-name=libsMc1206
project.catalog-coordinate=com.iamkaf.platform:mc-1.20.6:1.20.6-SNAPSHOT

mixin.compat.common=JAVA_21
mixin.compat.fabric=JAVA_21
mixin.compat.forge=JAVA_17
mixin.compat.neoforge=JAVA_21

mod.minecraft-range=[1.20.6, 1.21)
mod.fabric-range=>=1.20.6
mod.forge-loader-range=[50,)

dependencies.modrinth.required=amber
dependencies.curseforge.required=amber-lib
