project.minecraft=1.20.3
project.java=17
project.build-java=21
project.enabled-loaders=fabric,forge
project.catalog-name=libsMc1203
project.catalog-coordinate=com.iamkaf.platform:mc-1.20.3:1.20.3-SNAPSHOT
mod.minecraft-range=[1.20.3, 1.21)
mod.fabric-range=>=1.20.3
mod.forge-loader-range=[49,)
mixin.compat.common=JAVA_17
mixin.compat.fabric=JAVA_17
mixin.compat.forge=JAVA_17
mixin.compat.neoforge=JAVA_17

dependencies.curseforge.required=amber-lib
dependencies.modrinth.required=amber
project.version=5.0.0+1.20.3
