project.version=5.0.0+1.21.7
project.java=21
project.build-java=21
project.minecraft=1.21.7
project.enabled-loaders=fabric,forge,neoforge
project.catalog-name=libsMc1217
project.catalog-coordinate=com.iamkaf.platform:mc-1.21.7:1.21.7-SNAPSHOT

mixin.compat.common=JAVA_21
mixin.compat.fabric=JAVA_21
mixin.compat.forge=JAVA_21
mixin.compat.neoforge=JAVA_21

mod.minecraft-range=[1.21.7, 1.22)
mod.fabric-range=>=1.21.7
mod.forge-loader-range=[57,)
mod.neoforge-loader-range=[4,)

dependencies.modrinth.required=amber
dependencies.curseforge.required=amber-lib
